# Generated by Django 5.1.7 on 2025-03-31 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0003_alter_comment_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='image',
            field=models.URLField(blank=True, default=''),
        ),
    ]
